workflows:
  flutter-ios:
    name: Flutter iOS Build (Unsigned)
    environment:
      flutter: default
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install iOS Pods
        script: |
          cd ios
          pod install
      - name: Build iOS App (Unsigned)
        script: flutter build ios --release --no-codesign
      - name: Package into unsigned IPA
        script: |
          mkdir -p build/ios/ipa/Payload
          # Copying the built .app into the Payload folder
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          # Zipping it up into an .ipa file
          zip -qr app_hiu_unsigned.ipa Payload
    artifacts:
      - build/ios/ipa/app_hiu_unsigned.ipa